name: createBucket
on:
  push:
    branch:
      - main

env:
  AWS_REGION: us-east-1
  BUCKET_NAME: my-uno-bucket-demo-20226

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}

      - name: Create S3 bucket
        run: aws s3 mb s3://${{ env.BUCKET_NAME }}

      - name: create dummy file
        run: echo "Deployment successful" > test.txt

      - name: upload file to s3
        run: aws s3 cp test.txt s3://${{ env.BUCKET_NAME }}