name: Real Environment setup

on: [push]

jobs:
  check-environment:
    run-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Node Version
        run: node -v

      - name: Run Dependencies
        run: echo "in a real project we use npm install"
